// Do not edit. This file is machine generated by the Resource DLL Wizard.

library AnReDo;

{ITE} {DFMFileType} {ufrmAbout.dfm}
{ITE} {DFMFileType} {ufrmMain.dfm}
{ITE} {DFMFileType} {ufrmRepo.dfm}
{ITE} {RCFileType} {AnReDo_DRC.rc}

{$R 'ufrmAbout.dfm' frmAbout:TForm}
{$R 'ufrmMain.dfm' frmMain:TForm}
{$R 'ufrmRepo.dfm' frmRepo:TForm}
{$R 'AnReDo_DRC.res' 'AnReDo_DRC.rc'}

{$E RUS}

begin
end.